/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucb.juegos.buscaminas;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JButton;

/**
 *
 * @author ronal
 */
public class Principal extends javax.swing.JFrame {

    private Buscaminas buscaminas;

    private JButton botones[][];

    /**
     * Creates new form NewJFrame
     */
    public Principal() {
        initComponents();

        this.botones = new JButton[10][10];

        Component[] lista = jPanel1.getComponents();

        String s, fs, cs;
        int f, c;

        for (Component btn : lista) {
            s = btn.getName();

            fs = s.substring(0, 1);
            cs = s.substring(1, 2);

            f = Integer.parseInt(fs);
            c = Integer.parseInt(cs);

            this.botones[f][c] = (JButton) btn;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn00 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn07 = new javax.swing.JButton();
        btn08 = new javax.swing.JButton();
        btn09 = new javax.swing.JButton();
        btn10 = new javax.swing.JButton();
        btn11 = new javax.swing.JButton();
        btn12 = new javax.swing.JButton();
        btn13 = new javax.swing.JButton();
        btn14 = new javax.swing.JButton();
        btn15 = new javax.swing.JButton();
        btn16 = new javax.swing.JButton();
        btn17 = new javax.swing.JButton();
        btn18 = new javax.swing.JButton();
        btn19 = new javax.swing.JButton();
        btn20 = new javax.swing.JButton();
        btn21 = new javax.swing.JButton();
        btn22 = new javax.swing.JButton();
        btn23 = new javax.swing.JButton();
        btn24 = new javax.swing.JButton();
        btn25 = new javax.swing.JButton();
        btn26 = new javax.swing.JButton();
        btn27 = new javax.swing.JButton();
        btn28 = new javax.swing.JButton();
        btn29 = new javax.swing.JButton();
        btn30 = new javax.swing.JButton();
        btn31 = new javax.swing.JButton();
        btn32 = new javax.swing.JButton();
        btn33 = new javax.swing.JButton();
        btn34 = new javax.swing.JButton();
        btn35 = new javax.swing.JButton();
        btn36 = new javax.swing.JButton();
        btn37 = new javax.swing.JButton();
        btn38 = new javax.swing.JButton();
        btn39 = new javax.swing.JButton();
        btn40 = new javax.swing.JButton();
        btn41 = new javax.swing.JButton();
        btn42 = new javax.swing.JButton();
        btn43 = new javax.swing.JButton();
        btn44 = new javax.swing.JButton();
        btn45 = new javax.swing.JButton();
        btn46 = new javax.swing.JButton();
        btn47 = new javax.swing.JButton();
        btn48 = new javax.swing.JButton();
        btn49 = new javax.swing.JButton();
        btn50 = new javax.swing.JButton();
        btn51 = new javax.swing.JButton();
        btn52 = new javax.swing.JButton();
        btn53 = new javax.swing.JButton();
        btn54 = new javax.swing.JButton();
        btn55 = new javax.swing.JButton();
        btn56 = new javax.swing.JButton();
        btn57 = new javax.swing.JButton();
        btn58 = new javax.swing.JButton();
        btn59 = new javax.swing.JButton();
        btn60 = new javax.swing.JButton();
        btn61 = new javax.swing.JButton();
        btn62 = new javax.swing.JButton();
        btn63 = new javax.swing.JButton();
        btn64 = new javax.swing.JButton();
        btn65 = new javax.swing.JButton();
        btn66 = new javax.swing.JButton();
        btn67 = new javax.swing.JButton();
        btn68 = new javax.swing.JButton();
        btn69 = new javax.swing.JButton();
        btn70 = new javax.swing.JButton();
        btn71 = new javax.swing.JButton();
        btn72 = new javax.swing.JButton();
        btn73 = new javax.swing.JButton();
        btn74 = new javax.swing.JButton();
        btn75 = new javax.swing.JButton();
        btn76 = new javax.swing.JButton();
        btn77 = new javax.swing.JButton();
        btn78 = new javax.swing.JButton();
        btn79 = new javax.swing.JButton();
        btn80 = new javax.swing.JButton();
        btn81 = new javax.swing.JButton();
        btn82 = new javax.swing.JButton();
        btn83 = new javax.swing.JButton();
        btn84 = new javax.swing.JButton();
        btn85 = new javax.swing.JButton();
        btn86 = new javax.swing.JButton();
        btn87 = new javax.swing.JButton();
        btn88 = new javax.swing.JButton();
        btn89 = new javax.swing.JButton();
        btn90 = new javax.swing.JButton();
        btn91 = new javax.swing.JButton();
        btn92 = new javax.swing.JButton();
        btn93 = new javax.swing.JButton();
        btn94 = new javax.swing.JButton();
        btn95 = new javax.swing.JButton();
        btn96 = new javax.swing.JButton();
        btn97 = new javax.swing.JButton();
        btn98 = new javax.swing.JButton();
        btn99 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));

        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnVer.setText("Ver matrices");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new java.awt.GridLayout(10, 10, 2, 2));

        btn00.setMaximumSize(new java.awt.Dimension(34, 30));
        btn00.setMinimumSize(new java.awt.Dimension(34, 30));
        btn00.setName("00"); // NOI18N
        btn00.setPreferredSize(new java.awt.Dimension(42, 35));
        btn00.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn00);

        btn01.setMaximumSize(new java.awt.Dimension(34, 30));
        btn01.setMinimumSize(new java.awt.Dimension(34, 30));
        btn01.setName("01"); // NOI18N
        btn01.setPreferredSize(new java.awt.Dimension(42, 35));
        btn01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn01);

        btn02.setMaximumSize(new java.awt.Dimension(34, 30));
        btn02.setMinimumSize(new java.awt.Dimension(34, 30));
        btn02.setName("02"); // NOI18N
        btn02.setPreferredSize(new java.awt.Dimension(42, 35));
        btn02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn02);

        btn03.setMaximumSize(new java.awt.Dimension(34, 30));
        btn03.setMinimumSize(new java.awt.Dimension(34, 30));
        btn03.setName("03"); // NOI18N
        btn03.setPreferredSize(new java.awt.Dimension(42, 35));
        btn03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn03);

        btn04.setMaximumSize(new java.awt.Dimension(34, 30));
        btn04.setMinimumSize(new java.awt.Dimension(34, 30));
        btn04.setName("04"); // NOI18N
        btn04.setPreferredSize(new java.awt.Dimension(42, 35));
        btn04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn04);

        btn05.setMaximumSize(new java.awt.Dimension(34, 30));
        btn05.setMinimumSize(new java.awt.Dimension(34, 30));
        btn05.setName("05"); // NOI18N
        btn05.setPreferredSize(new java.awt.Dimension(42, 35));
        btn05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn05);

        btn06.setMaximumSize(new java.awt.Dimension(34, 30));
        btn06.setMinimumSize(new java.awt.Dimension(34, 30));
        btn06.setName("06"); // NOI18N
        btn06.setPreferredSize(new java.awt.Dimension(42, 35));
        btn06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn06);

        btn07.setMaximumSize(new java.awt.Dimension(34, 30));
        btn07.setMinimumSize(new java.awt.Dimension(34, 30));
        btn07.setName("07"); // NOI18N
        btn07.setPreferredSize(new java.awt.Dimension(42, 35));
        btn07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn07);

        btn08.setMaximumSize(new java.awt.Dimension(34, 30));
        btn08.setMinimumSize(new java.awt.Dimension(34, 30));
        btn08.setName("08"); // NOI18N
        btn08.setPreferredSize(new java.awt.Dimension(42, 35));
        btn08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn08);

        btn09.setMaximumSize(new java.awt.Dimension(34, 30));
        btn09.setMinimumSize(new java.awt.Dimension(34, 30));
        btn09.setName("09"); // NOI18N
        btn09.setPreferredSize(new java.awt.Dimension(42, 35));
        btn09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn09);

        btn10.setMaximumSize(new java.awt.Dimension(34, 30));
        btn10.setMinimumSize(new java.awt.Dimension(34, 30));
        btn10.setName("10"); // NOI18N
        btn10.setPreferredSize(new java.awt.Dimension(42, 35));
        btn10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn10);

        btn11.setMaximumSize(new java.awt.Dimension(34, 30));
        btn11.setMinimumSize(new java.awt.Dimension(34, 30));
        btn11.setName("11"); // NOI18N
        btn11.setPreferredSize(new java.awt.Dimension(42, 35));
        btn11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn11);

        btn12.setMaximumSize(new java.awt.Dimension(34, 30));
        btn12.setMinimumSize(new java.awt.Dimension(34, 30));
        btn12.setName("12"); // NOI18N
        btn12.setPreferredSize(new java.awt.Dimension(42, 35));
        btn12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn12);

        btn13.setMaximumSize(new java.awt.Dimension(34, 30));
        btn13.setMinimumSize(new java.awt.Dimension(34, 30));
        btn13.setName("13"); // NOI18N
        btn13.setPreferredSize(new java.awt.Dimension(42, 35));
        btn13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn13);

        btn14.setMaximumSize(new java.awt.Dimension(34, 30));
        btn14.setMinimumSize(new java.awt.Dimension(34, 30));
        btn14.setName("14"); // NOI18N
        btn14.setPreferredSize(new java.awt.Dimension(42, 35));
        btn14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn14);

        btn15.setMaximumSize(new java.awt.Dimension(34, 30));
        btn15.setMinimumSize(new java.awt.Dimension(34, 30));
        btn15.setName("15"); // NOI18N
        btn15.setPreferredSize(new java.awt.Dimension(42, 35));
        btn15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn15);

        btn16.setMaximumSize(new java.awt.Dimension(34, 30));
        btn16.setMinimumSize(new java.awt.Dimension(34, 30));
        btn16.setName("16"); // NOI18N
        btn16.setPreferredSize(new java.awt.Dimension(42, 35));
        btn16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn16);

        btn17.setMaximumSize(new java.awt.Dimension(34, 30));
        btn17.setMinimumSize(new java.awt.Dimension(34, 30));
        btn17.setName("17"); // NOI18N
        btn17.setPreferredSize(new java.awt.Dimension(42, 35));
        btn17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn17);

        btn18.setMaximumSize(new java.awt.Dimension(34, 30));
        btn18.setMinimumSize(new java.awt.Dimension(34, 30));
        btn18.setName("18"); // NOI18N
        btn18.setPreferredSize(new java.awt.Dimension(42, 35));
        btn18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn18);

        btn19.setMaximumSize(new java.awt.Dimension(34, 30));
        btn19.setMinimumSize(new java.awt.Dimension(34, 30));
        btn19.setName("19"); // NOI18N
        btn19.setPreferredSize(new java.awt.Dimension(42, 35));
        btn19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn19);

        btn20.setMaximumSize(new java.awt.Dimension(34, 30));
        btn20.setMinimumSize(new java.awt.Dimension(34, 30));
        btn20.setName("20"); // NOI18N
        btn20.setPreferredSize(new java.awt.Dimension(42, 35));
        btn20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn20);

        btn21.setMaximumSize(new java.awt.Dimension(34, 30));
        btn21.setMinimumSize(new java.awt.Dimension(34, 30));
        btn21.setName("21"); // NOI18N
        btn21.setPreferredSize(new java.awt.Dimension(42, 35));
        btn21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn21);

        btn22.setMaximumSize(new java.awt.Dimension(34, 30));
        btn22.setMinimumSize(new java.awt.Dimension(34, 30));
        btn22.setName("22"); // NOI18N
        btn22.setPreferredSize(new java.awt.Dimension(42, 35));
        btn22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn22);

        btn23.setMaximumSize(new java.awt.Dimension(34, 30));
        btn23.setMinimumSize(new java.awt.Dimension(34, 30));
        btn23.setName("23"); // NOI18N
        btn23.setPreferredSize(new java.awt.Dimension(42, 35));
        btn23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn23);

        btn24.setMaximumSize(new java.awt.Dimension(34, 30));
        btn24.setMinimumSize(new java.awt.Dimension(34, 30));
        btn24.setName("24"); // NOI18N
        btn24.setPreferredSize(new java.awt.Dimension(42, 35));
        btn24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn24);

        btn25.setMaximumSize(new java.awt.Dimension(34, 30));
        btn25.setMinimumSize(new java.awt.Dimension(34, 30));
        btn25.setName("25"); // NOI18N
        btn25.setPreferredSize(new java.awt.Dimension(42, 35));
        btn25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn25);

        btn26.setMaximumSize(new java.awt.Dimension(34, 30));
        btn26.setMinimumSize(new java.awt.Dimension(34, 30));
        btn26.setName("26"); // NOI18N
        btn26.setPreferredSize(new java.awt.Dimension(42, 35));
        btn26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn26);

        btn27.setMaximumSize(new java.awt.Dimension(34, 30));
        btn27.setMinimumSize(new java.awt.Dimension(34, 30));
        btn27.setName("27"); // NOI18N
        btn27.setPreferredSize(new java.awt.Dimension(42, 35));
        btn27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn27);

        btn28.setMaximumSize(new java.awt.Dimension(34, 30));
        btn28.setMinimumSize(new java.awt.Dimension(34, 30));
        btn28.setName("28"); // NOI18N
        btn28.setPreferredSize(new java.awt.Dimension(42, 35));
        btn28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn28);

        btn29.setMaximumSize(new java.awt.Dimension(34, 30));
        btn29.setMinimumSize(new java.awt.Dimension(34, 30));
        btn29.setName("29"); // NOI18N
        btn29.setPreferredSize(new java.awt.Dimension(42, 35));
        btn29.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn29);

        btn30.setMaximumSize(new java.awt.Dimension(34, 30));
        btn30.setMinimumSize(new java.awt.Dimension(34, 30));
        btn30.setName("30"); // NOI18N
        btn30.setPreferredSize(new java.awt.Dimension(42, 35));
        btn30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn30);

        btn31.setMaximumSize(new java.awt.Dimension(34, 30));
        btn31.setMinimumSize(new java.awt.Dimension(34, 30));
        btn31.setName("31"); // NOI18N
        btn31.setPreferredSize(new java.awt.Dimension(42, 35));
        btn31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn31);

        btn32.setMaximumSize(new java.awt.Dimension(34, 30));
        btn32.setMinimumSize(new java.awt.Dimension(34, 30));
        btn32.setName("32"); // NOI18N
        btn32.setPreferredSize(new java.awt.Dimension(42, 35));
        btn32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn32);

        btn33.setMaximumSize(new java.awt.Dimension(34, 30));
        btn33.setMinimumSize(new java.awt.Dimension(34, 30));
        btn33.setName("33"); // NOI18N
        btn33.setPreferredSize(new java.awt.Dimension(42, 35));
        btn33.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn33);

        btn34.setMaximumSize(new java.awt.Dimension(34, 30));
        btn34.setMinimumSize(new java.awt.Dimension(34, 30));
        btn34.setName("34"); // NOI18N
        btn34.setPreferredSize(new java.awt.Dimension(42, 35));
        btn34.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn34);

        btn35.setMaximumSize(new java.awt.Dimension(34, 30));
        btn35.setMinimumSize(new java.awt.Dimension(34, 30));
        btn35.setName("35"); // NOI18N
        btn35.setPreferredSize(new java.awt.Dimension(42, 35));
        btn35.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn35);

        btn36.setMaximumSize(new java.awt.Dimension(34, 30));
        btn36.setMinimumSize(new java.awt.Dimension(34, 30));
        btn36.setName("36"); // NOI18N
        btn36.setPreferredSize(new java.awt.Dimension(42, 35));
        btn36.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn36);

        btn37.setMaximumSize(new java.awt.Dimension(34, 30));
        btn37.setMinimumSize(new java.awt.Dimension(34, 30));
        btn37.setName("37"); // NOI18N
        btn37.setPreferredSize(new java.awt.Dimension(42, 35));
        btn37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn37);

        btn38.setMaximumSize(new java.awt.Dimension(34, 30));
        btn38.setMinimumSize(new java.awt.Dimension(34, 30));
        btn38.setName("38"); // NOI18N
        btn38.setPreferredSize(new java.awt.Dimension(42, 35));
        btn38.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn38);

        btn39.setMaximumSize(new java.awt.Dimension(34, 30));
        btn39.setMinimumSize(new java.awt.Dimension(34, 30));
        btn39.setName("39"); // NOI18N
        btn39.setPreferredSize(new java.awt.Dimension(42, 35));
        btn39.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn39);

        btn40.setMaximumSize(new java.awt.Dimension(34, 30));
        btn40.setMinimumSize(new java.awt.Dimension(34, 30));
        btn40.setName("40"); // NOI18N
        btn40.setPreferredSize(new java.awt.Dimension(42, 35));
        btn40.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn40);

        btn41.setMaximumSize(new java.awt.Dimension(34, 30));
        btn41.setMinimumSize(new java.awt.Dimension(34, 30));
        btn41.setName("41"); // NOI18N
        btn41.setPreferredSize(new java.awt.Dimension(42, 35));
        btn41.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn41);

        btn42.setMaximumSize(new java.awt.Dimension(34, 30));
        btn42.setMinimumSize(new java.awt.Dimension(34, 30));
        btn42.setName("42"); // NOI18N
        btn42.setPreferredSize(new java.awt.Dimension(42, 35));
        btn42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn42);

        btn43.setMaximumSize(new java.awt.Dimension(34, 30));
        btn43.setMinimumSize(new java.awt.Dimension(34, 30));
        btn43.setName("43"); // NOI18N
        btn43.setPreferredSize(new java.awt.Dimension(42, 35));
        btn43.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn43);

        btn44.setMaximumSize(new java.awt.Dimension(34, 30));
        btn44.setMinimumSize(new java.awt.Dimension(34, 30));
        btn44.setName("44"); // NOI18N
        btn44.setPreferredSize(new java.awt.Dimension(42, 35));
        btn44.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn44);

        btn45.setMaximumSize(new java.awt.Dimension(34, 30));
        btn45.setMinimumSize(new java.awt.Dimension(34, 30));
        btn45.setName("45"); // NOI18N
        btn45.setPreferredSize(new java.awt.Dimension(42, 35));
        btn45.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn45);

        btn46.setMaximumSize(new java.awt.Dimension(34, 30));
        btn46.setMinimumSize(new java.awt.Dimension(34, 30));
        btn46.setName("46"); // NOI18N
        btn46.setPreferredSize(new java.awt.Dimension(42, 35));
        btn46.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn46);

        btn47.setMaximumSize(new java.awt.Dimension(34, 30));
        btn47.setMinimumSize(new java.awt.Dimension(34, 30));
        btn47.setName("47"); // NOI18N
        btn47.setPreferredSize(new java.awt.Dimension(42, 35));
        btn47.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn47);

        btn48.setMaximumSize(new java.awt.Dimension(34, 30));
        btn48.setMinimumSize(new java.awt.Dimension(34, 30));
        btn48.setName("48"); // NOI18N
        btn48.setPreferredSize(new java.awt.Dimension(42, 35));
        btn48.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn48);

        btn49.setMaximumSize(new java.awt.Dimension(34, 30));
        btn49.setMinimumSize(new java.awt.Dimension(34, 30));
        btn49.setName("49"); // NOI18N
        btn49.setPreferredSize(new java.awt.Dimension(42, 35));
        btn49.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn49);

        btn50.setMaximumSize(new java.awt.Dimension(34, 30));
        btn50.setMinimumSize(new java.awt.Dimension(34, 30));
        btn50.setName("50"); // NOI18N
        btn50.setPreferredSize(new java.awt.Dimension(42, 35));
        btn50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn50);

        btn51.setMaximumSize(new java.awt.Dimension(34, 30));
        btn51.setMinimumSize(new java.awt.Dimension(34, 30));
        btn51.setName("51"); // NOI18N
        btn51.setPreferredSize(new java.awt.Dimension(42, 35));
        btn51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn51);

        btn52.setMaximumSize(new java.awt.Dimension(34, 30));
        btn52.setMinimumSize(new java.awt.Dimension(34, 30));
        btn52.setName("52"); // NOI18N
        btn52.setPreferredSize(new java.awt.Dimension(42, 35));
        btn52.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn52);

        btn53.setMaximumSize(new java.awt.Dimension(34, 30));
        btn53.setMinimumSize(new java.awt.Dimension(34, 30));
        btn53.setName("53"); // NOI18N
        btn53.setPreferredSize(new java.awt.Dimension(42, 35));
        btn53.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn53);

        btn54.setMaximumSize(new java.awt.Dimension(34, 30));
        btn54.setMinimumSize(new java.awt.Dimension(34, 30));
        btn54.setName("54"); // NOI18N
        btn54.setPreferredSize(new java.awt.Dimension(42, 35));
        btn54.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn54);

        btn55.setMaximumSize(new java.awt.Dimension(34, 30));
        btn55.setMinimumSize(new java.awt.Dimension(34, 30));
        btn55.setName("55"); // NOI18N
        btn55.setPreferredSize(new java.awt.Dimension(42, 35));
        btn55.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn55);

        btn56.setMaximumSize(new java.awt.Dimension(34, 30));
        btn56.setMinimumSize(new java.awt.Dimension(34, 30));
        btn56.setName("56"); // NOI18N
        btn56.setPreferredSize(new java.awt.Dimension(42, 35));
        btn56.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn56);

        btn57.setMaximumSize(new java.awt.Dimension(34, 30));
        btn57.setMinimumSize(new java.awt.Dimension(34, 30));
        btn57.setName("57"); // NOI18N
        btn57.setPreferredSize(new java.awt.Dimension(42, 35));
        btn57.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn57);

        btn58.setMaximumSize(new java.awt.Dimension(34, 30));
        btn58.setMinimumSize(new java.awt.Dimension(34, 30));
        btn58.setName("58"); // NOI18N
        btn58.setPreferredSize(new java.awt.Dimension(42, 35));
        btn58.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn58);

        btn59.setMaximumSize(new java.awt.Dimension(34, 30));
        btn59.setMinimumSize(new java.awt.Dimension(34, 30));
        btn59.setName("59"); // NOI18N
        btn59.setPreferredSize(new java.awt.Dimension(42, 35));
        btn59.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn59);

        btn60.setMaximumSize(new java.awt.Dimension(34, 30));
        btn60.setMinimumSize(new java.awt.Dimension(34, 30));
        btn60.setName("60"); // NOI18N
        btn60.setPreferredSize(new java.awt.Dimension(42, 35));
        btn60.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn60);

        btn61.setMaximumSize(new java.awt.Dimension(34, 30));
        btn61.setMinimumSize(new java.awt.Dimension(34, 30));
        btn61.setName("61"); // NOI18N
        btn61.setPreferredSize(new java.awt.Dimension(42, 35));
        btn61.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn61);

        btn62.setMaximumSize(new java.awt.Dimension(34, 30));
        btn62.setMinimumSize(new java.awt.Dimension(34, 30));
        btn62.setName("62"); // NOI18N
        btn62.setPreferredSize(new java.awt.Dimension(42, 35));
        btn62.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn62);

        btn63.setMaximumSize(new java.awt.Dimension(34, 30));
        btn63.setMinimumSize(new java.awt.Dimension(34, 30));
        btn63.setName("63"); // NOI18N
        btn63.setPreferredSize(new java.awt.Dimension(42, 35));
        btn63.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn63);

        btn64.setMaximumSize(new java.awt.Dimension(34, 30));
        btn64.setMinimumSize(new java.awt.Dimension(34, 30));
        btn64.setName("64"); // NOI18N
        btn64.setPreferredSize(new java.awt.Dimension(42, 35));
        btn64.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn64);

        btn65.setMaximumSize(new java.awt.Dimension(34, 30));
        btn65.setMinimumSize(new java.awt.Dimension(34, 30));
        btn65.setName("65"); // NOI18N
        btn65.setPreferredSize(new java.awt.Dimension(42, 35));
        btn65.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn65);

        btn66.setMaximumSize(new java.awt.Dimension(34, 30));
        btn66.setMinimumSize(new java.awt.Dimension(34, 30));
        btn66.setName("66"); // NOI18N
        btn66.setPreferredSize(new java.awt.Dimension(42, 35));
        btn66.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn66);

        btn67.setMaximumSize(new java.awt.Dimension(34, 30));
        btn67.setMinimumSize(new java.awt.Dimension(34, 30));
        btn67.setName("67"); // NOI18N
        btn67.setPreferredSize(new java.awt.Dimension(42, 35));
        btn67.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn67);

        btn68.setMaximumSize(new java.awt.Dimension(34, 30));
        btn68.setMinimumSize(new java.awt.Dimension(34, 30));
        btn68.setName("68"); // NOI18N
        btn68.setPreferredSize(new java.awt.Dimension(42, 35));
        btn68.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn68);

        btn69.setMaximumSize(new java.awt.Dimension(34, 30));
        btn69.setMinimumSize(new java.awt.Dimension(34, 30));
        btn69.setName("69"); // NOI18N
        btn69.setPreferredSize(new java.awt.Dimension(42, 35));
        btn69.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn69);

        btn70.setMaximumSize(new java.awt.Dimension(34, 30));
        btn70.setMinimumSize(new java.awt.Dimension(34, 30));
        btn70.setName("70"); // NOI18N
        btn70.setPreferredSize(new java.awt.Dimension(42, 35));
        btn70.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn70);

        btn71.setMaximumSize(new java.awt.Dimension(34, 30));
        btn71.setMinimumSize(new java.awt.Dimension(34, 30));
        btn71.setName("71"); // NOI18N
        btn71.setPreferredSize(new java.awt.Dimension(42, 35));
        btn71.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn71);

        btn72.setMaximumSize(new java.awt.Dimension(34, 30));
        btn72.setMinimumSize(new java.awt.Dimension(34, 30));
        btn72.setName("72"); // NOI18N
        btn72.setPreferredSize(new java.awt.Dimension(42, 35));
        btn72.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn72);

        btn73.setMaximumSize(new java.awt.Dimension(34, 30));
        btn73.setMinimumSize(new java.awt.Dimension(34, 30));
        btn73.setName("73"); // NOI18N
        btn73.setPreferredSize(new java.awt.Dimension(42, 35));
        btn73.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn73);

        btn74.setMaximumSize(new java.awt.Dimension(34, 30));
        btn74.setMinimumSize(new java.awt.Dimension(34, 30));
        btn74.setName("74"); // NOI18N
        btn74.setPreferredSize(new java.awt.Dimension(42, 35));
        btn74.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn74);

        btn75.setMaximumSize(new java.awt.Dimension(34, 30));
        btn75.setMinimumSize(new java.awt.Dimension(34, 30));
        btn75.setName("75"); // NOI18N
        btn75.setPreferredSize(new java.awt.Dimension(42, 35));
        btn75.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn75);

        btn76.setMaximumSize(new java.awt.Dimension(34, 30));
        btn76.setMinimumSize(new java.awt.Dimension(34, 30));
        btn76.setName("76"); // NOI18N
        btn76.setPreferredSize(new java.awt.Dimension(42, 35));
        btn76.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn76);

        btn77.setMaximumSize(new java.awt.Dimension(34, 30));
        btn77.setMinimumSize(new java.awt.Dimension(34, 30));
        btn77.setName("77"); // NOI18N
        btn77.setPreferredSize(new java.awt.Dimension(42, 35));
        btn77.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn77);

        btn78.setMaximumSize(new java.awt.Dimension(34, 30));
        btn78.setMinimumSize(new java.awt.Dimension(34, 30));
        btn78.setName("78"); // NOI18N
        btn78.setPreferredSize(new java.awt.Dimension(42, 35));
        btn78.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn78);

        btn79.setMaximumSize(new java.awt.Dimension(34, 30));
        btn79.setMinimumSize(new java.awt.Dimension(34, 30));
        btn79.setName("79"); // NOI18N
        btn79.setPreferredSize(new java.awt.Dimension(42, 35));
        btn79.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn79);

        btn80.setMaximumSize(new java.awt.Dimension(34, 30));
        btn80.setMinimumSize(new java.awt.Dimension(34, 30));
        btn80.setName("80"); // NOI18N
        btn80.setPreferredSize(new java.awt.Dimension(42, 35));
        btn80.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn80);

        btn81.setMaximumSize(new java.awt.Dimension(34, 30));
        btn81.setMinimumSize(new java.awt.Dimension(34, 30));
        btn81.setName("81"); // NOI18N
        btn81.setPreferredSize(new java.awt.Dimension(42, 35));
        btn81.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn81);

        btn82.setMaximumSize(new java.awt.Dimension(34, 30));
        btn82.setMinimumSize(new java.awt.Dimension(34, 30));
        btn82.setName("82"); // NOI18N
        btn82.setPreferredSize(new java.awt.Dimension(42, 35));
        btn82.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn82);

        btn83.setMaximumSize(new java.awt.Dimension(34, 30));
        btn83.setMinimumSize(new java.awt.Dimension(34, 30));
        btn83.setName("83"); // NOI18N
        btn83.setPreferredSize(new java.awt.Dimension(42, 35));
        btn83.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn83);

        btn84.setMaximumSize(new java.awt.Dimension(34, 30));
        btn84.setMinimumSize(new java.awt.Dimension(34, 30));
        btn84.setName("84"); // NOI18N
        btn84.setPreferredSize(new java.awt.Dimension(42, 35));
        btn84.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn84);

        btn85.setMaximumSize(new java.awt.Dimension(34, 30));
        btn85.setMinimumSize(new java.awt.Dimension(34, 30));
        btn85.setName("85"); // NOI18N
        btn85.setPreferredSize(new java.awt.Dimension(42, 35));
        btn85.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn85);

        btn86.setMaximumSize(new java.awt.Dimension(34, 30));
        btn86.setMinimumSize(new java.awt.Dimension(34, 30));
        btn86.setName("86"); // NOI18N
        btn86.setPreferredSize(new java.awt.Dimension(42, 35));
        btn86.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn86);

        btn87.setMaximumSize(new java.awt.Dimension(34, 30));
        btn87.setMinimumSize(new java.awt.Dimension(34, 30));
        btn87.setName("87"); // NOI18N
        btn87.setPreferredSize(new java.awt.Dimension(42, 35));
        btn87.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn87);

        btn88.setMaximumSize(new java.awt.Dimension(34, 30));
        btn88.setMinimumSize(new java.awt.Dimension(34, 30));
        btn88.setName("88"); // NOI18N
        btn88.setPreferredSize(new java.awt.Dimension(42, 35));
        btn88.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn88);

        btn89.setMaximumSize(new java.awt.Dimension(34, 30));
        btn89.setMinimumSize(new java.awt.Dimension(34, 30));
        btn89.setName("89"); // NOI18N
        btn89.setPreferredSize(new java.awt.Dimension(42, 35));
        btn89.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn89);

        btn90.setMaximumSize(new java.awt.Dimension(34, 30));
        btn90.setMinimumSize(new java.awt.Dimension(34, 30));
        btn90.setName("90"); // NOI18N
        btn90.setPreferredSize(new java.awt.Dimension(42, 35));
        btn90.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn90);

        btn91.setMaximumSize(new java.awt.Dimension(34, 30));
        btn91.setMinimumSize(new java.awt.Dimension(34, 30));
        btn91.setName("91"); // NOI18N
        btn91.setPreferredSize(new java.awt.Dimension(42, 35));
        btn91.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn91);

        btn92.setMaximumSize(new java.awt.Dimension(34, 30));
        btn92.setMinimumSize(new java.awt.Dimension(34, 30));
        btn92.setName("92"); // NOI18N
        btn92.setPreferredSize(new java.awt.Dimension(42, 35));
        btn92.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn92);

        btn93.setMaximumSize(new java.awt.Dimension(34, 30));
        btn93.setMinimumSize(new java.awt.Dimension(34, 30));
        btn93.setName("93"); // NOI18N
        btn93.setPreferredSize(new java.awt.Dimension(42, 35));
        btn93.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn93);

        btn94.setMaximumSize(new java.awt.Dimension(34, 30));
        btn94.setMinimumSize(new java.awt.Dimension(34, 30));
        btn94.setName("94"); // NOI18N
        btn94.setPreferredSize(new java.awt.Dimension(42, 35));
        btn94.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn94);

        btn95.setMaximumSize(new java.awt.Dimension(34, 30));
        btn95.setMinimumSize(new java.awt.Dimension(34, 30));
        btn95.setName("95"); // NOI18N
        btn95.setPreferredSize(new java.awt.Dimension(42, 35));
        btn95.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn95);

        btn96.setMaximumSize(new java.awt.Dimension(34, 30));
        btn96.setMinimumSize(new java.awt.Dimension(34, 30));
        btn96.setName("96"); // NOI18N
        btn96.setPreferredSize(new java.awt.Dimension(42, 35));
        btn96.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn96);

        btn97.setMaximumSize(new java.awt.Dimension(34, 30));
        btn97.setMinimumSize(new java.awt.Dimension(34, 30));
        btn97.setName("97"); // NOI18N
        btn97.setPreferredSize(new java.awt.Dimension(42, 35));
        btn97.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn97);

        btn98.setMaximumSize(new java.awt.Dimension(34, 30));
        btn98.setMinimumSize(new java.awt.Dimension(34, 30));
        btn98.setName("98"); // NOI18N
        btn98.setPreferredSize(new java.awt.Dimension(42, 35));
        btn98.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn98);

        btn99.setMaximumSize(new java.awt.Dimension(34, 30));
        btn99.setMinimumSize(new java.awt.Dimension(34, 30));
        btn99.setName("99"); // NOI18N
        btn99.setPreferredSize(new java.awt.Dimension(42, 35));
        btn99.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                clicBoton(evt);
            }
        });
        jPanel1.add(btn99);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnVer)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        this.buscaminas.mostrar(); //muestra en la consola las matrices
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        this.buscaminas = new Buscaminas();
        this.buscaminas.inicializar();

        this.buscaminas.mostrar();

        for (int i = 0; i < 10; i++) {
            for (int j = 0; j < 10; j++) {
                this.botones[i][j].setText("");
            }

        }

    }//GEN-LAST:event_btnNuevoActionPerformed

    private void clicBoton(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clicBoton

        JButton btn = (JButton) evt.getSource();

        String s = btn.getName();

        int f = Integer.parseInt(s.substring(0, 1));
        int c = Integer.parseInt(s.substring(1, 2));

        switch (evt.getButton()) {
            case 1: //botón izquierdo
                this.buscaminas.jugar(f, c);
                btn.setText(String.valueOf(this.buscaminas.minas[f][c]));
                btn.setBackground(Color.gray);
                break;
            case 3: //botón derecho
                this.buscaminas.marcar(f, c);
                btn.setText("*");
                break;
        }

    }//GEN-LAST:event_clicBoton

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn00;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn08;
    private javax.swing.JButton btn09;
    private javax.swing.JButton btn10;
    private javax.swing.JButton btn11;
    private javax.swing.JButton btn12;
    private javax.swing.JButton btn13;
    private javax.swing.JButton btn14;
    private javax.swing.JButton btn15;
    private javax.swing.JButton btn16;
    private javax.swing.JButton btn17;
    private javax.swing.JButton btn18;
    private javax.swing.JButton btn19;
    private javax.swing.JButton btn20;
    private javax.swing.JButton btn21;
    private javax.swing.JButton btn22;
    private javax.swing.JButton btn23;
    private javax.swing.JButton btn24;
    private javax.swing.JButton btn25;
    private javax.swing.JButton btn26;
    private javax.swing.JButton btn27;
    private javax.swing.JButton btn28;
    private javax.swing.JButton btn29;
    private javax.swing.JButton btn30;
    private javax.swing.JButton btn31;
    private javax.swing.JButton btn32;
    private javax.swing.JButton btn33;
    private javax.swing.JButton btn34;
    private javax.swing.JButton btn35;
    private javax.swing.JButton btn36;
    private javax.swing.JButton btn37;
    private javax.swing.JButton btn38;
    private javax.swing.JButton btn39;
    private javax.swing.JButton btn40;
    private javax.swing.JButton btn41;
    private javax.swing.JButton btn42;
    private javax.swing.JButton btn43;
    private javax.swing.JButton btn44;
    private javax.swing.JButton btn45;
    private javax.swing.JButton btn46;
    private javax.swing.JButton btn47;
    private javax.swing.JButton btn48;
    private javax.swing.JButton btn49;
    private javax.swing.JButton btn50;
    private javax.swing.JButton btn51;
    private javax.swing.JButton btn52;
    private javax.swing.JButton btn53;
    private javax.swing.JButton btn54;
    private javax.swing.JButton btn55;
    private javax.swing.JButton btn56;
    private javax.swing.JButton btn57;
    private javax.swing.JButton btn58;
    private javax.swing.JButton btn59;
    private javax.swing.JButton btn60;
    private javax.swing.JButton btn61;
    private javax.swing.JButton btn62;
    private javax.swing.JButton btn63;
    private javax.swing.JButton btn64;
    private javax.swing.JButton btn65;
    private javax.swing.JButton btn66;
    private javax.swing.JButton btn67;
    private javax.swing.JButton btn68;
    private javax.swing.JButton btn69;
    private javax.swing.JButton btn70;
    private javax.swing.JButton btn71;
    private javax.swing.JButton btn72;
    private javax.swing.JButton btn73;
    private javax.swing.JButton btn74;
    private javax.swing.JButton btn75;
    private javax.swing.JButton btn76;
    private javax.swing.JButton btn77;
    private javax.swing.JButton btn78;
    private javax.swing.JButton btn79;
    private javax.swing.JButton btn80;
    private javax.swing.JButton btn81;
    private javax.swing.JButton btn82;
    private javax.swing.JButton btn83;
    private javax.swing.JButton btn84;
    private javax.swing.JButton btn85;
    private javax.swing.JButton btn86;
    private javax.swing.JButton btn87;
    private javax.swing.JButton btn88;
    private javax.swing.JButton btn89;
    private javax.swing.JButton btn90;
    private javax.swing.JButton btn91;
    private javax.swing.JButton btn92;
    private javax.swing.JButton btn93;
    private javax.swing.JButton btn94;
    private javax.swing.JButton btn95;
    private javax.swing.JButton btn96;
    private javax.swing.JButton btn97;
    private javax.swing.JButton btn98;
    private javax.swing.JButton btn99;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnVer;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
